   res = instance.__dict__[self.name] = self.func(instance)
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/Ecomprj/ecommerce/ecommerce/urls.py", line 4, in <module>
    from .views import home  # Import the home view
ModuleNotFoundError: No module named 'ecommerce.views'
/workspaces/Ecomprj/ecommerce/ecommerce/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 05, 2024 - 04:45:56
Django version 5.0.7, using settings 'ecommerce.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[05/Aug/2024 04:45:59] "GET / HTTP/1.1" 200 9
[05/Aug/2024 04:46:16] "GET / HTTP/1.1" 200 9
[05/Aug/2024 04:46:21] "GET /admin/login/?next=/login/ HTTP/1.1" 200 4158
[05/Aug/2024 04:46:21] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[05/Aug/2024 04:46:21] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[05/Aug/2024 04:46:21] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[05/Aug/2024 04:46:21] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[05/Aug/2024 04:46:21] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[05/Aug/2024 04:46:21] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[05/Aug/2024 04:46:21] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[05/Aug/2024 04:46:29] "POST /admin/login/?next=/login/ HTTP/1.1" 302 0
Internal Server Error: /login/
Traceback (most recent call last):
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/workspaces/Ecomprj/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
[05/Aug/2024 04:46:29] "GET /login/ HTTP/1.1" 500 90347